# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/ihuntgore/Users/Juan/Documents/proyectos/python/qtdesigner/practica1/views/vista_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background-color: white;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.head = QtWidgets.QFrame(self.centralwidget)
        self.head.setMinimumSize(QtCore.QSize(0, 90))
        self.head.setMaximumSize(QtCore.QSize(16777215, 90))
        self.head.setStyleSheet("QFrame {\n"
"    background-color: #16a085;\n"
"}")
        self.head.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.head.setFrameShadow(QtWidgets.QFrame.Raised)
        self.head.setObjectName("head")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.head)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.title = QtWidgets.QLabel(self.head)
        self.title.setStyleSheet("QLabel {\n"
"    font: bold 20pt \"sans-serif\";\n"
"    color: white;\n"
"}")
        self.title.setObjectName("title")
        self.gridLayout_3.addWidget(self.title, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.head)
        self.body = QtWidgets.QFrame(self.centralwidget)
        self.body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body.setObjectName("body")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.body)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.body)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_10 = QtWidgets.QFrame(self.frame_6)
        self.frame_10.setMinimumSize(QtCore.QSize(800, 100))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_nombre = QtWidgets.QLabel(self.frame_10)
        self.lbl_nombre.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_nombre.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_nombre.setStyleSheet("QLabel {\n"
"    padding: 0 0 0 30;\n"
"}")
        self.lbl_nombre.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.horizontalLayout_4.addWidget(self.lbl_nombre, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_3.addWidget(self.frame_10)
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 360))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 600))
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.txta_nombre = QtWidgets.QTextEdit(self.frame_9)
        self.txta_nombre.setEnabled(True)
        self.txta_nombre.setMinimumSize(QtCore.QSize(500, 50))
        self.txta_nombre.setMaximumSize(QtCore.QSize(920, 50))
        self.txta_nombre.setStyleSheet("QTextEdit {\n"
"    border-radius: 10px;\n"
"    border: 1px solid;\n"
"    margin: 0 auto 0 20;\n"
"}")
        self.txta_nombre.setObjectName("txta_nombre")
        self.horizontalLayout_3.addWidget(self.txta_nombre, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_2.addWidget(self.frame_9, 0, QtCore.Qt.AlignTop)
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setMinimumSize(QtCore.QSize(140, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(140, 16777215))
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_saludar = QtWidgets.QPushButton(self.frame_8)
        self.btn_saludar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_saludar.setMouseTracking(False)
        self.btn_saludar.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    background-color: #16a085;\n"
"    color: white;\n"
"    font: bold 12pt \"sans-serif\";\n"
"    padding: 10px 0px;\n"
"}")
        self.btn_saludar.setObjectName("btn_saludar")
        self.gridLayout_2.addWidget(self.btn_saludar, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_8, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.body)
        self.foot = QtWidgets.QFrame(self.centralwidget)
        self.foot.setMaximumSize(QtCore.QSize(16777215, 61))
        self.foot.setStyleSheet("QFrame {\n"
"    background-color: #1abc9c;\n"
"}")
        self.foot.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.foot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.foot.setObjectName("foot")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.foot)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.foot)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.foot)
        self.frame_4.setMinimumSize(QtCore.QSize(160, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(160, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_sobre = QtWidgets.QPushButton(self.frame_4)
        self.btn_sobre.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_sobre.setStyleSheet("QPushButton {\n"
"    border-radius: 20px;\n"
"    background-color: white;\n"
"    color: black;\n"
"    font: bold 12pt \"sans-serif\";\n"
"    padding: 10px 0px;\n"
"}")
        self.btn_sobre.setObjectName("btn_sobre")
        self.gridLayout.addWidget(self.btn_sobre, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.foot)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Aplicacion simple usando MVC"))
        self.lbl_nombre.setText(_translate("MainWindow", "Nombre"))
        self.btn_saludar.setText(_translate("MainWindow", "Saludar"))
        self.btn_sobre.setText(_translate("MainWindow", "Sobre la App"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
